#server:
#  port: 8080
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer

resilience4j:
  ratelimiter:
    instances:
      customerService:
        limit-for-period: 2 # 2 request per 10 second
        limit-refresh-period: 10s # 10 second refresh limits
        timeout-duration: 0s # immidetly reject not allow request without waiting

  circuitbreaker:
    instances:
      fraudServiceCircuitBreaker:
#       Sliding window configuration
        sliding-window-type: COUNT_BASED
        sliding-window-size: 6
        minimum-number-of-calls: 5

#       Failure Threshold
        failure-rate-threshold: 50

#       Open state configuration
        wait-duration-in-open-state:  10s

#       Half Open state Configuration
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true

        record-exceptions:
          - java.lang.RuntimeException
          - java.io.IOException
          - org.springframework.web.client.HttpServerErrorException

        ignore-exceptions:
          - java.lang.IllegalArgumentException


#  datasource:
#    password: 1234
#    url: jdbc:postgresql://localhost:5432/customer
#    username: user
#  jpa:
#    hibernate:
####      ddl-auto: create-drop
#      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: true
####    database: postgresql
####    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    baseline-description: 'init'
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka
#    fetch-registry: true
#    register-with-eureka: true
#    eureka-server-port: 8761
#application:
#  config:
#    fraud-url: http://localhost:8081/api/v1/fraud-check
