#server:
#  port: 8081
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: fraud
#  datasource:
#    password: 1234
#    url: jdbc:postgresql://localhost:5432/fraud
#    username: user
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: true
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka
#    fetch-registry: true
#    register-with-eureka: true
#    eureka-server-port: 8761
