server:
  port: 8080
spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/customer
    username: user
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
#      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  ##    database: postgresql
  ##    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    baseline-description: 'init'
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: customerConfirmation:com.example.microservice.customer.record.CustomerConfirmation

application:
  config:
    fraud-url: http://localhost:8081/api/v1/fraud-check


#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka
#    fetch-registry: true
#    register-with-eureka: true
#    eureka-server-port: 8761

