server:
  port: 8081
spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/fraud
    username: user
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: registerNotificationRequest:com.example.microservice.fraud.record.RegisterNotificationRequest

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka
#    fetch-registry: true
#    register-with-eureka: true
#    eureka-server-port: 8761
