server:
  port: 8040
spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/notification
    username: user
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: customerGroup, fraudGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: customerConfirmation:com.example.microservice.notification.kafka.customer.CustomerConfirmation,fraudConfirmation:com.example.microservice.notification.kafka.fraud.FraudConfirmation
  mail:
    host: localhost
    port: 1025
    username: Lahiru
    password: Lahiru
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
